# Generated by Django 4.2.3 on 2023-08-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autopassport'),
        ),
    ]
